---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-openresty
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    env USERNAMEDD;
    http {
      server {
        listen 80 default_server;
        server_name _;

        default_type text/plain;

        set_by_lua $username 'return os.getenv("USERNAMEDD")';
        location / {
          return 200 'Hello, $username, I am $hostname\n';
        }
      }
    }
...
