---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: super-app
  template:
    metadata:
      labels:
        app: super-app
    spec:
      containers:
      - image: debian:jessie
        name: debian
        command: ['sh', '-c', 'while true; do echo "Hello, $USERNAME"; sleep 2; done']
        env:
          - name: USERNAME
            value: ElectroDude 60
        ports:
        - containerPort: 80
...
